export const ActivityType = {
    SESSION_STARTED: "SESSION_STARTED",
    SESSION_COMPLETED: "SESSION_COMPLETED",
    SESSION_PAUSED: "SESSION_PAUSED",
    SESSION_RESUMED: "SESSION_RESUMED",
    SESSION_CANCELLED: "SESSION_CANCELLED",
    SESSION_FAILED: "SESSION_FAILED",
    SESSION_DELETED: "SESSION_DELETED",

    CALIBRATION_STARTED: "CALIBRATION_STARTED",
    CALIBRATION_COMPLETED: "CALIBRATION_COMPLETED",
    CALIBRATION_FAILED: "CALIBRATION_FAILED",
    CALIBRATION_UPDATED: "CALIBRATION_UPDATED",
    CALIBRATION_RESET: "CALIBRATION_RESET",

    TRACKING_STARTED: "TRACKING_STARTED",
    TRACKING_STOPPED: "TRACKING_STOPPED",
    TRACKING_PAUSED: "TRACKING_PAUSED",
    TRACKING_RESUMED: "TRACKING_RESUMED",
    TRACKING_LOST: "TRACKING_LOST",
    TRACKING_RECONNECTED: "TRACKING_RECONNECTED",

    DEVICE_CONNECTED: "DEVICE_CONNECTED",
    DEVICE_DISCONNECTED: "DEVICE_DISCONNECTED",
    DEVICE_RECONNECTED: "DEVICE_RECONNECTED",
    DEVICE_UPDATED: "DEVICE_UPDATED",
    DEVICE_ERROR: "DEVICE_ERROR",

    ANALYSIS_COMPLETED: "ANALYSIS_COMPLETED",
    ANALYSIS_FAILED: "ANALYSIS_FAILED",
    ANALYSIS_UPDATED: "ANALYSIS_UPDATED",

    REPORT_GENERATED: "REPORT_GENERATED",
    REPORT_UPDATED: "REPORT_UPDATED",
    REPORT_DOWNLOADED: "REPORT_DOWNLOADED",
    REPORT_DELETED: "REPORT_DELETED",

    PROFILE_UPDATED: "PROFILE_UPDATED",
    AVATAR_UPDATED: "AVATAR_UPDATED",
    PASSWORD_CHANGED: "PASSWORD_CHANGED",

    MODEL_CREATED: "MODEL_CREATED",
    MODEL_UPDATED: "MODEL_UPDATED",
    MODEL_SELECTED: "MODEL_SELECTED",
    MODEL_TRAINING_COMPLETED: "MODEL_TRAINING_COMPLETED",
    MODEL_TRAINING_FAILED: "MODEL_TRAINING_FAILED"
};